### PR TITLE
Testing Pull request from SergeyLee in SmartGit application.

### PR DESCRIPTION
**Pull request by SergeyLee**

### CODE REVIEW

**Comment by deruelle** [comment]
Thanks Sergey. It's working.

**Comment by deruelle** [comment]
FYI, I created a CloudBees CI Job for Continuous Delivery of this Resource Adaptor. You can see https://mobicents.ci.cloudbees.com/job/Mobicents-JDBC-RA/. So you can use 2.8.1 as version for this RA for the JAIN SLEE build.xml

**Comment by SergeyLee** [comment]
Ok! Today and tomorrow I will create many pull requests.
Some of them with changes of year in code Copyrigth or Document. These changes are needed?
On JDBC I see CloudBees, and I need login for it. On sergey.povarnin@mobius-software.com.
Thanks!

**Comment by deruelle** [comment]
You can change the copyright date and header file only for the files in
which you actually do a code change.
I added you as user to cloudbees you should have received a separate email
for login access.

Jean

**Comment by SergeyLee** [comment]
I understand.
I haven't received email for login access yet.
And I'm currently working on TCK. I have load it from your repo: https://github.com/deruelle/mobicents.
Should I add folder /tck in Mobicents repo jain-slee? I have some questions on it now.

**Comment by deruelle** [comment]
Maybe check your spam folder ?
On the TCK, please get it from the official repo
https://github.com/Mobicents/jain-slee.more/

**Comment by SergeyLee** [comment]
Thanks! I try official TCK now.
And I try login to CloudBees (email isn't received yet) with my GitHub account, and it work!
Where I can ask questions about testing Enablers? How I must test them? Must I write some SBB code?

**Comment by deruelle** [comment]
You can write on the
https://groups.google.com/forum/#!forum/mobicents-public for those enablers
questions.

**Comment by SergeyLee** [comment]
Ok. I used this group for searching answers. I have joined to it today and added 2 topics, but they are invisible. :(

**Pull request merged**
